[build]
  publish = "public"
  command = "hugo --gc --minify"

  [build.environment]
    HUGO_VERSION = "0.128.2"

[context.production.environment]
  HUGO_ENV = "production"

[context.split1]
  command = "hugo --gc --minify"

  [context.split1.environment]
    HUGO_ENV = "production"