[build]
  publish = "public"
  command = "hugo --gc --minify"

  [build.environment]
    GO_VERSION = "1.25.3"
    HUGO_VERSION = "0.152.2"
    NODE_VERSION = "22.20.0"

[context.production.environment]
  HUGO_ENV = "production"

[context.split1]
  command = "hugo --gc --minify"

  [context.split1.environment]
    HUGO_ENV = "production"